language: node_js
node_js:
- '6'
- '6.1'
install:
- npm install
deploy:
  app: client-api-example
  provider: heroku
  api_key:
    secure: EFWLG214xeJraSqao9Y9PuC7OVFTeRoZYXOhXduzqR0Om+vWr4JvcfJEqZt0XUpPCjEnGSvUALrxnisCibD6JG5cJwFZGWuh44UvHfJS5E/PaOeDq+EXRE29S5zSQrDJxZBjsUgZChZALK9T0JEGUNJODmZYBAOz6IOA1G0mrpT0pU7TBYlvNuJ+YyUuhyRIxmYHZ0Gg3J6PbN0pgWPPtQLkHEh4B5u4y60RIFQzmoE5GLE24NtYDLI9gBpas5k2FWfZsTaxXizVs2zOaGgylG0E1aQ/oahFxH5oPN30Vjv4cP1VnbggfIuBcyZKPdOpG0hpz+IqbYXtBbui//Lm9+MnasQvSWSaQpvcR8KbdKff78TFVHxI4nHbsMIfJGaUCahcCj5Tp/l5CXkUeLvXNKW1vRBoWz45Euetz7mcAg8z/Tgx+6ctmkPIhGK7NVN6ccKplYiVCVUUNes06hlzRVyTq2tOcvz4XgPyXPCt8Y1yljrXkEzjmaWkWtE8/VnRdruQBaYU8vlg4kGMeKyUCSoFYEHIJLRvt2ij+ayTCUjC3cm/qoS4UnEHwDaee3bZ/ZCF3tSBO+r69Y4DeB2WSLqL8jAxbRO6GOUxo+CXbLEPjlKXI7EEX9NsPRzYYGfn0hvT8dVdxwfU64mufrD0tt+k+tE6IlJIgHsk6wL33AY=
